# Site settings
title: "Pinyao Song Resume"
description: "Resume of Pinyao Song"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Pinyao Song"
resume_title:                   "UQ Human-Centred Computing Ph.D. Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "p.song at uq.edu.au"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "xxx"
resume_contact_address:         "UQ"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello! I am Pinyao, a PhD canditiate in HCI at The University of Queensland. I am doing my last year of my PhD and about to graduate by the end of the year, so currently on <strong>JOB MARKET</strong>. 
I'm co-supervised by <a href='https://about.uq.edu.au/experts/24135'> Dr Dhaval Vyas </a> and <a href='https://communication-arts.uq.edu.au/profile/370/aparna-hebbani'> Dr Aparna Hebbani </a>. My current research focus includes co-design with vulnerable communities. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
